### PR TITLE
remove binstubs

### PR DESCRIPTION
**Pull request by mpapis**
Using `--binstubs` with `$PATH` is not secure - more details here => http://niczsoft.com/2013/10/please-hack-my-rails/

I have changed the commands for something that will work for everybody and those who use shortcuts will know how to use them.

I also have seen `--binstubs` in other projects, like https://github.com/capistrano/rails  https://github.com/capistrano/capistrano ... and few more, should I open PR for each of them or can someone with commit rights to every of them do the fix?

### CODE REVIEW

**Comment by kirs** [comment]
Well, as we have binstubs in all capistrano-\* repos and it would be better to start from the main one.

**Comment by Kriechi** [comment]
Since capistrano itself merged it, I would suggest to merge it here too.

@kirs can you do that please, and then push out a new gem version?

**Comment by kirs** [comment]
Sure. Do we need to push a new version with just a README change?

**Comment by Kriechi** [comment]
Ah sorry, my mistake. I thought there were more changes since the last release.
Nevermind.

**Pull request merged**
