### PR TITLE
improved README

### PR DESCRIPTION
**Pull request by Kriechi**
unified README parts according to the other capistrano-\* gems.
clarified that the described settings _do not_ need to be added, because they are default anyway.
removed the version selector on L15, maybe we should add '~> 1.0' after we bump the gem to 1.0
removed the instruction to execute `cap install` - which of course is rubbish.

### CODE REVIEW

**Comment by kirs** [comment]
> Or install it yourself as:

could you remove this section?
I don't believe there are any ruby projects that use capistrano and rvm without bundler.

**Comment by Kriechi** [comment]
I added it, because it is present in capistrano-bundler.
Should we remove it there too?

**Comment by kirs** [comment]
Yep

**Comment by Kriechi** [comment]
I have updated this PR as requested.

**Comment by Kriechi** [comment]
@kirs anything holding this back any further?

**Comment by kirs** [comment]
Thanks!

**Pull request merged**
