### PR TITLE
fix: Don't know how to build task 'rvm:hook'

### PR DESCRIPTION
**Pull request by flo-ruby-shanghai**
Moved the deploy => after :starting at the end of file otherwhise, it triggers the task 'rvm:hook' before it's been declared

### CODE REVIEW

**Comment by flo-ruby-shanghai** [comment]
Fix for capistrano 3.1.0, not 3.0.1

**Comment by Kriechi** [comment]
This will be solved once #22 is merged.

**Comment by systemiv** [comment]
i have this problem, and i don't know how this fixed.
This is my deploy.rb.
https://gist.github.com/systemiv/d334f422383de2ce4b11

Here trace https://gist.github.com/systemiv/836f1c68d4bf0f86abd0

**Comment by kirs** [comment]
@systemiv Gist says your files are deleted

**Comment by kirs** [comment]
The issue is supposed to be fixed by https://github.com/capistrano/rvm/pull/22

**Pull request closed without merging**
