### PR TITLE
remove using wrappers, fix #13, fix #14

### LINKED ISSUE #13: capistrano/rvm fails with system wide rvm instalation
I'm porting capistrano 2 + rvm-capistrano deployment to capitrano 3 + capistrano/rvm. I use system wide rvm instalation and unprivileged user for deployment. Looks like capistrano/rvm tries to write to system wide rvm installation:

```
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:init (first_time)
** Execute rvm:init
** Invoke rvm:create_wrappers (first_time)
** Execute rvm:create_wrappers
 INFO [a80551dd] Running /usr/local/rvm/bin/rvm wrapper 2.0.0-p247 app_name bundle gem rake ruby on app.domain.com
DEBUG [a80551dd] Command: /usr/local/rvm/bin/rvm wrapper 2.0.0-p247 app_name bundle gem rake ruby
DEBUG [a80551dd]    No bin path suitable for lining wrapper. Try setting 'rvm_bin_path'.
cap aborted!
rvm stdout: Nothing written
rvm stderr: Nothing written
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/command.rb:94:in `exit_status='
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:125:in `block (4 levels) in _execute'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/channel.rb:551:in `call'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/channel.rb:551:in `do_request'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:561:in `channel_request'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:205:in `process'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/channel.rb:269:in `wait'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:147:in `block (2 levels) in _execute'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/channel.rb:514:in `call'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:205:in `process'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:149:in `block in _execute'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:106:in `tap'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:106:in `_execute'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:54:in `execute'
/home/user/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rvm-05e37c4ec2f6/lib/capistrano/tasks/rvm.rake:68:in `block (3 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:42:in `instance_exec'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/backends/netssh.rb:42:in `run'
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.0.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => rvm:create_wrappers
```

### LINKED ISSUE #14: Check that :application is set.
If it isn't set, it attempts to produce a wrapper like this:

`INFO [689ab449] Running /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247  bundle gem rake ruby on sandbox`

rather than:
`INFO [689ab449] Running /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247 my_app bundle gem rake ruby on sandbox`

It would be better to raise an exception saying you must set application, or provide a default.

### PR DESCRIPTION
**Pull request by mpapis**
switch to detect the binaries at runtime using `rvm ruby do binary` - this eliminates the need to create wrappers which solves:
- #13 - no need to write anything
- #14 - no need to check application for creating wrappers

### CODE REVIEW

**Comment by kirs** [comment]
It's a nice feature and it simplifies RVM integration a lot, but I think we need more testing by users.

**Comment by mpapis** [comment]
I also think it needs more testing, but this is one of basic features of rvm so I do not expect problems, 

it will also allow adding flags like `--create` and `--install`:

``` bash
rvm ruby@gemset --create --install do binary
```

**Comment by Kriechi** [comment]
@mpapis could you please updated the readme according to your changes.
(once it's tested enough and your proposed solution works)

**Comment by Zeophlite** [comment]
I'm using this PR in my production code, so +1 for pulling

It integrates well with capistrano/bundler/pull/6

**Comment by Kriechi** [comment]
:+1: for pulling

**Comment by kirs** [comment]
Thanks for testing! I've pushed `0.0.3` version of the gem and it's ready to use :blush:

**Pull request merged**
