### PR TITLE
renamed rvm task file to use .cap extension

### PR DESCRIPTION
**Pull request by Kriechi**
use .cap file extension for Capistrano DSL tasks.

### CODE REVIEW

**Comment by kirs** [comment]
I'm not sure it's a good idea. This change may break code highlighting and GH language detector.

**Comment by Kriechi** [comment]
Well, Capistrano searches for `*.cap` files.
capistrano-bundler uses `.cap`.
capistrano-rails uses `.rake`

I just want it to be unified - which one I don't care :smiley:

**Comment by Kriechi** [comment]
Maybe @leehambley or @seenmyfate have a strong opinion in either side and could decide which file extensions all capistrano-\* tasks should use.

**Comment by leehambley** [comment]
"whatever makes syntax highlighting easier" is my opinion. If we take .cap, at least it's clear for people like myself who use a lot of Cap, and Rake + SSHKit what is what. I expect the cap DSL to be available on main in .cap files. 

I believe we have a mix in the core, we should sort that out, really.

```
➜  capistrano git:(master) find . -name '*.cap'
./spec/support/tasks/database.cap
./spec/support/tasks/fail.cap
./spec/support/tasks/failed.cap
➜  capistrano git:(master) find . -name '*.rake'
./lib/capistrano/tasks/console.rake
./lib/capistrano/tasks/deploy.rake
./lib/capistrano/tasks/framework.rake
./lib/capistrano/tasks/git.rake
./lib/capistrano/tasks/hg.rake
./lib/capistrano/tasks/install.rake
```

I'm also not opposed to putting Vim and Emacs formatting/highlighting cues in the head of those files, as a well as Ruby encoding markers, and then making the extension `.cap`.

If we decide to do that (just give me a -/+1) I can do it.

**Comment by Kriechi** [comment]
:+1: for the .cap extension for everything with Capistrano-DSL inside.

If we should add editor-specific headers for syntax selection, I am not sure.
vim/emacs/textmate/sublime and many others... I think it would be better to not include anything at all, and let each developer handle this on their own. just my 2 cents on that.

**Comment by kirs** [comment]
:+1: for *.rake only.

**Pull request closed without merging**
