### PR TITLE
suppress this constant RVM checks if QUIET environment variables is set.

### PR DESCRIPTION
**Pull request by bretweinraub**
latest versions of capistrano are so slow that these redundant checks add lots of time to deploys and are only necessary for debugging.

maybe there's a more cap-fu way to suppress them; but for me they run for every deploy and invoke target.

it doesn't help that EACH  cap execute command run in its own sshkit session .... grind, wait, yawn.

### CODE REVIEW

**Comment by kirs** [comment]
> it doesn't help that EACH cap execute command run in its own sshkit session .... grind, wait, yawn.

It was improved on SSHKit 1.3 and now it has connection pool. Did you try it?

It's a good idea to skip some rvm checks, but I don't think that `ENV['QUIET']` is meaningful.

**Comment by Kriechi** [comment]
Maybe just do the checks if `loglevel == :debug`?

**Comment by bretweinraub** [comment]
I like the loglevel idea.  Couldn't find a single shred of documentation on how to set it.

But it is fact set via this in your deploy.rb

set :log_level, :info

**Comment by bretweinraub** [comment]
? Maybe just do the checks if loglevel == :debug?

ok done

```
  if fetch(:log_level) == :debug
    puts capture(:rvm, "version")
    puts capture(:rvm, "current")
    puts capture(:ruby, "--version")
  end
```

**Comment by bretweinraub** [comment]
In my environment, this save 4.1 seconds off my deploy.

**Comment by penso** [comment]
Saving 3sec easy here too, that should definitely be a log level variable.

**Comment by pangratz** [comment]
Stumbled upon this today. This would be very useful being in master.

**Comment by kirs** [comment]
Thanks!

**Comment by bretweinraub** [comment]
Yes!

**Pull request merged**
