### PR TITLE
Add support for mixed mode installations

### PR DESCRIPTION
**Pull request by kernow**
Mixed mode installations need to use the system locations for the rvm command and the user location for wrapped commands. What do you think about this for adding support for mixed mode installs?

### CODE REVIEW

**Comment by kirs** [comment]
I was using RVM for a while and never saw such mixed installations in production. Not sure if it's good practice at all.

**Comment by kernow** [comment]
There is a rather specific use case for this setup where most users of the server are not allowed to install rubies but can install gems. Only privileged users can install rubies. It's a feature of rvm so I'd argue it should be supported by the gem as it doesn't currently work with a mixed mode installation.

**Comment by mpapis** [comment]
RVM mixed mode is just a system installation with extra settings in `~/.rvmrc`, I do encourage it in some cases when there is a need to separate management of ruby from application deploy (see #9).

**Comment by kirs** [comment]
Thanks!

**Pull request merged**
